command: "jefes"
nopermissions: "&cYou dont have permissions to do this"
bossDropsHeader: "&bEl jugador &e%player% &bha derrotado a %boss% &by ha soltado:"
dropLine: "   - &e%item% &ex%amount%"
header: "&d=============================================="
available: "&b - &e%boss_name% &bis available"
oncooldown: "&b - &e%boss_name% &bis on cooldown for &e%boss_cooldown%"
footer: "&d=============================================="
blacklist:
  - "exampleMob1"
  - "exampleMob2"