name: MMUtils
version: 1.2
main: wbe.mmutils.MMUtils
api-version: 1.20.4
author: wbe
depend: [MythicMobs]
commands:
  Bosses:
    description: MMUtils main command
    aliases: [boss]
    permission: mmutils.command
